"""M3 adapter: compile an AGR graph into runnable framework source.

Code generation, not a runtime dependency: the emitted module is self-contained
(embeds the condition evaluator), wires the full topology into a StateGraph, and
leaves each node as a NotImplementedError stub declaring the speciality/abilities
the implementer (human or agent) must bind. Structure is compiled; behavior is bound.
"""
from __future__ import annotations

from .subgraphs import expand, has_subgraphs


def _executable(doc: dict) -> dict:
    """The graph the harness actually runs.

    A `kind: subgraph` phase has no behaviour of its own — it stands for the
    child graph's whole topology. Compiling the unexpanded doc emitted one
    `NotImplementedError` stub per phase and silently dropped the child, so the
    generated module implemented a different graph from the one `agr eval` runs.
    Every emitter expands first.
    """
    return expand(doc) if has_subgraphs(doc) else doc


def _criteria(n: dict) -> str:
    """A node's rubric, escaped for embedding in a generated double-quoted string.

    Every emitter carries it. The stub (or the CrewAI goal, or the AutoGen system
    message) is where a human or an agent binds behavior, so it is exactly where
    the domain knowledge has to arrive — leaving it in a YAML file the implementer
    is not reading is how a "healthcare graph" ends up containing no healthcare.
    """
    return (n.get("criteria") or "").replace("\\", "\\\\").replace('"', '\\"')


def _fn(node_id: str) -> str:
    # Expanded subgraph ids carry a dot (`implement.plan`); both it and the
    # dash are illegal in a Python identifier.
    return "node_" + node_id.replace("-", "_").replace(".", "_")


#: The emitted module is self-contained by design, so the allowlist that
#: `agenticgraphs.safeexpr` applies at eval time is inlined here rather than
#: imported. Without it, every generated LangGraph/CrewAI/AutoGen app shipped
#: the escape `{"__builtins__": {}}` never closed.
_EMITTED_GUARD = '''\
import ast as _ast

_ALLOWED_NODES = {
    "Expression", "BoolOp", "And", "Or", "UnaryOp", "Not", "IfExp", "Compare",
    "Eq", "NotEq", "Lt", "LtE", "Gt", "GtE", "Is", "IsNot", "In", "NotIn",
    "BinOp", "Add", "Sub", "Mult", "Div", "Mod", "Name", "Load", "Attribute",
    "Constant", "Subscript", "Slice", "List", "Tuple", "Set", "Dict", "Call",
    "GeneratorExp", "ListComp", "SetComp", "comprehension", "Store",
}
_CALLABLE_NAMES = {"len", "all", "any", "sum", "min", "max", "abs", "round"}


def _safe_expr(expr: str):
    """Compile `expr` only if every node is allowlisted. Returns None otherwise."""
    try:
        tree = _ast.parse(expr, mode="eval")
    except SyntaxError:
        return None
    for node in _ast.walk(tree):
        if type(node).__name__ not in _ALLOWED_NODES:
            return None
        if isinstance(node, _ast.Attribute) and node.attr.startswith("_"):
            return None
        if isinstance(node, _ast.Name) and node.id.startswith("_"):
            return None
        if isinstance(node, _ast.Call):
            fn = node.func
            if isinstance(fn, _ast.Attribute):
                if fn.attr != "get":
                    return None
            elif isinstance(fn, _ast.Name):
                if fn.id not in _CALLABLE_NAMES:
                    return None
            else:
                return None
    return compile(tree, "<agr-expr>", "eval")
'''

_PRELUDE = _EMITTED_GUARD + '''\
from langgraph.graph import END, START, StateGraph

_ORDER = {"trivial": -1, "low": 0, "simple": 0, "medium": 1, "moderate": 1,
          "high": 2, "complex": 2, "critical": 3}


def _cond(expr: str, state: dict) -> bool:
    class _L:
        def __init__(self, s): self.v = _ORDER[s]
        def __le__(self, o): return self.v <= _v(o)
        def __lt__(self, o): return self.v < _v(o)
        def __ge__(self, o): return self.v >= _v(o)
        def __gt__(self, o): return self.v > _v(o)
        def __eq__(self, o): return self.v == _v(o)
        def __hash__(self): return hash(self.v)

    def _v(o):
        return o.v if isinstance(o, _L) else _ORDER.get(o)

    ns = {"true": True, "false": False, "len": len, "all": all, "any": any,
          **{k: _L(k) for k in _ORDER}, **state}
    code = _safe_expr(expr)
    if code is None:
        return False  # refused by the allowlist: not a condition, not taken
    try:
        return bool(eval(code, {"__builtins__": {}}, ns))
    except Exception:
        return False
'''


def emit_langgraph(doc: dict) -> str:
    doc = _executable(doc)
    out = [f'"""LangGraph build of AGR graph `{doc["name"]}` — generated by `agr adapt`.',
           "", f'Contract: {doc["termination"]["contract"]}', '"""', _PRELUDE]
    for n in doc["nodes"]:
        abilities = ", ".join(n.get("abilities", []))
        # The stub is where a human or an agent binds behavior, so it is exactly
        # where the rubric has to arrive. Emitting only the speciality handed the
        # implementer a role label and left the domain knowledge in a YAML file
        # they were not reading.
        doc_lines = [f'speciality: {n["speciality"]} | abilities: {abilities}']
        if n.get("criteria"):
            doc_lines += ["", f'Must judge: {n["criteria"]}']
        body = "\n    ".join(doc_lines)
        out += [f"def {_fn(n['id'])}(state: dict) -> dict:",
                f'    """{body}"""',
                f"    raise NotImplementedError(\"bind speciality '{n['speciality']}'"
                f" (abilities: {abilities})\")", ""]
    out += ["g = StateGraph(dict)"]
    for n in doc["nodes"]:
        out.append(f'g.add_node("{n["id"]}", {_fn(n["id"])})')
    has_in = {e["to"] for e in doc["edges"]}
    has_out: dict[str, list] = {}
    for e in doc["edges"]:
        has_out.setdefault(e["from"], []).append(e)
    for n in doc["nodes"]:
        if n["id"] not in has_in:
            out.append(f'g.add_edge(START, "{n["id"]}")')
    for n in doc["nodes"]:
        edges = has_out.get(n["id"], [])
        if not edges:
            out.append(f'g.add_edge("{n["id"]}", END)')
        elif all(not e.get("when") for e in edges):
            out += [f'g.add_edge("{n["id"]}", "{e["to"]}")' for e in edges]
        else:
            rf = "_route_" + _fn(n["id"])[5:]
            pairs = ", ".join(f'("{e["to"]}", {e.get("when")!r})' for e in edges)
            first_match = n.get("kind") == "router"
            out += [f"def {rf}(state: dict):",
                    f"    hits = [t for t, w in [{pairs}] if w is None or _cond(w, state)]",
                    ("    return hits[0] if hits else END" if first_match
                     else "    return hits or END"),
                    f'g.add_conditional_edges("{n["id"]}", {rf})']
    out += ["", "app = g.compile()", ""]
    return "\n".join(out)


def emit_crewai(doc: dict) -> str:
    doc = _executable(doc)
    """Compile an AGR graph into runnable-shaped CrewAI source.

    Nodes become Agents (speciality -> role; abilities left as a TODO tool
    list, since AGR abilities are not CrewAI tool objects). Edges become
    Tasks, with any `when` conditions surfaced as conditional-routing notes
    in the task description (CrewAI's sequential Process has no native
    branching primitive). The termination contract becomes the
    `expected_output` of the graph's terminal task(s).
    """
    contract = doc.get("termination", {}).get("contract") or f"completion of {doc['name']}"
    out = [f'"""CrewAI build of AGR graph `{doc["name"]}` — generated by `agr adapt --target crewai`.',
           "", f"Contract: {contract}", '"""',
           "from crewai import Agent, Crew, Process, Task", ""]

    for n in doc["nodes"]:
        var = _fn(n["id"])
        abilities = ", ".join(n.get("abilities", [])) or "none declared"
        out += [f"{var}_agent = Agent(",
                f'    role="{n["speciality"]}",',
                (f'    goal="{_criteria(n)}",' if _criteria(n)
                 else f'    goal="perform the \'{n["id"]}\' step of {doc["name"]}",'),
                f'    backstory="specialised in {n["speciality"]}",',
                f"    tools=[],  # TODO: bind abilities ({abilities}) to real CrewAI tools",
                "    allow_delegation=False,", ")", ""]

    has_out: dict[str, list] = {}
    for e in doc["edges"]:
        has_out.setdefault(e["from"], []).append(e)
    terminals = {n["id"] for n in doc["nodes"] if n["id"] not in has_out}

    for n in doc["nodes"]:
        var = _fn(n["id"])
        edges = has_out.get(n["id"], [])
        routes = "; ".join(f'-> {e["to"]} when {e["when"]}' if e.get("when") else f'-> {e["to"]}' for e in edges)
        desc = f"execute '{n['id']}' ({n['speciality']})."
        if routes:
            desc += f" Conditional routing: {routes}."
        expected = contract if n["id"] in terminals else f"structured output consumed by the next step in {doc['name']}"
        out += [f"{var}_task = Task(",
                f'    description="{desc}",',
                f'    expected_output="{expected}",',
                f"    agent={var}_agent,", ")", ""]

    agents = ", ".join(f"{_fn(n['id'])}_agent" for n in doc["nodes"])
    tasks = ", ".join(f"{_fn(n['id'])}_task" for n in doc["nodes"])
    out += ["crew = Crew(", f"    agents=[{agents}],", f"    tasks=[{tasks}],",
            "    process=Process.sequential,", ")", ""]
    return "\n".join(out)


_AUTOGEN_COND = _EMITTED_GUARD + '''\
def _cond(expr: str, state: dict) -> bool:
    class _L:
        def __init__(self, s): self.v = _ORDER[s]
        def __le__(self, o): return self.v <= _v(o)
        def __lt__(self, o): return self.v < _v(o)
        def __ge__(self, o): return self.v >= _v(o)
        def __gt__(self, o): return self.v > _v(o)
        def __eq__(self, o): return self.v == _v(o)
        def __hash__(self): return hash(self.v)

    def _v(o):
        return o.v if isinstance(o, _L) else _ORDER.get(o)

    ns = {"true": True, "false": False, "len": len, "all": all, "any": any,
          **{k: _L(k) for k in _ORDER}, **state}
    code = _safe_expr(expr)
    if code is None:
        return False  # refused by the allowlist: not a condition, not taken
    try:
        return bool(eval(code, {"__builtins__": {}}, ns))
    except Exception:
        return False
'''


def emit_autogen(doc: dict) -> str:
    doc = _executable(doc)
    """Compile an AGR graph into runnable-shaped AutoGen source.

    Nodes become ConversableAgent/AssistantAgent definitions. Router-kind
    nodes' outgoing `when` conditions are encoded into a GroupChat
    speaker-selection function (`_select_speaker`), reusing the same
    Level-aware condition evaluator the LangGraph emitter embeds. The
    termination contract becomes each agent's `is_termination_msg`.
    """
    contract = doc.get("termination", {}).get("contract") or f"completion of {doc['name']}"
    out = [f'"""AutoGen build of AGR graph `{doc["name"]}` — generated by `agr adapt --target autogen`.',
           "", f"Contract: {contract}", '"""',
           "from autogen import AssistantAgent, ConversableAgent, GroupChat, GroupChatManager", "",
           '_ORDER = {"trivial": -1, "low": 0, "simple": 0, "medium": 1, "moderate": 1,',
           '          "high": 2, "complex": 2, "critical": 3}', ""]

    out += ['def is_termination_msg(msg: dict) -> bool:',
            f'    """Contract: {contract}"""',
            '    return isinstance(msg, dict) and bool(msg.get("terminate"))', ""]

    for n in doc["nodes"]:
        var = _fn(n["id"])
        abilities = ", ".join(n.get("abilities", [])) or "none declared"
        cls = "ConversableAgent" if n.get("kind") == "human" else "AssistantAgent"
        out += [f"{var} = {cls}(",
                f'    name="{n["id"]}",',
                (f'    system_message="You are a {n["speciality"]} agent. Abilities: '
                 f'{abilities}. Must judge: {_criteria(n)}",' if _criteria(n) else
                 f'    system_message="You are a {n["speciality"]} agent. Abilities: {abilities}.",'),
                "    is_termination_msg=is_termination_msg,", ")", ""]

    has_out: dict[str, list] = {}
    for e in doc["edges"]:
        has_out.setdefault(e["from"], []).append(e)

    out += ["def _select_speaker(last_speaker, groupchat):",
            '    """Speaker selection encoding AGR edge conditions (`when`) as Python."""',
            '    state = groupchat.messages[-1].get("state", {}) if groupchat.messages else {}',
            "    routes = {"]
    for node_id, edges in has_out.items():
        pairs = ", ".join(f'("{e["to"]}", {e.get("when")!r})' for e in edges)
        out.append(f'        "{node_id}": [{pairs}],')
    out += ["    }",
            "    agents = {a.name: a for a in groupchat.agents}",
            '    for to, when in routes.get(getattr(last_speaker, "name", None), []):',
            "        if when is None or _cond(when, state):",
            "            return agents.get(to)",
            "    return None", ""]
    out.append(_AUTOGEN_COND)

    agent_vars = ", ".join(_fn(n["id"]) for n in doc["nodes"])
    max_steps = doc.get("termination", {}).get("max_steps", 10)
    out += [f"groupchat = GroupChat(agents=[{agent_vars}], messages=[], max_round={max_steps},",
            "                      speaker_selection_method=_select_speaker)",
            "manager = GroupChatManager(groupchat=groupchat)", ""]
    return "\n".join(out)
