"""M3 adapter: compile an AGR graph into runnable LangGraph source.

Code generation, not a runtime dependency: the emitted module is self-contained
(embeds the condition evaluator), wires the full topology into a StateGraph, and
leaves each node as a NotImplementedError stub declaring the speciality/abilities
the implementer (human or agent) must bind. Structure is compiled; behavior is bound.
"""
from __future__ import annotations


def _fn(node_id: str) -> str:
    return "node_" + node_id.replace("-", "_")


_PRELUDE = '''\
from langgraph.graph import END, START, StateGraph

_ORDER = {"trivial": -1, "low": 0, "simple": 0, "medium": 1, "moderate": 1,
          "high": 2, "complex": 2, "critical": 3}


def _cond(expr: str, state: dict) -> bool:
    class _L:
        def __init__(self, s): self.v = _ORDER[s]
        def __le__(self, o): return self.v <= _v(o)
        def __lt__(self, o): return self.v < _v(o)
        def __ge__(self, o): return self.v >= _v(o)
        def __gt__(self, o): return self.v > _v(o)
        def __eq__(self, o): return self.v == _v(o)
        def __hash__(self): return hash(self.v)

    def _v(o):
        return o.v if isinstance(o, _L) else _ORDER.get(o)

    ns = {"true": True, "false": False, "len": len, "all": all, "any": any,
          **{k: _L(k) for k in _ORDER}, **state}
    try:
        return bool(eval(expr, {"__builtins__": {}}, ns))
    except Exception:
        return False
'''


def emit_langgraph(doc: dict) -> str:
    out = [f'"""LangGraph build of AGR graph `{doc["name"]}` — generated by `agr adapt`.',
           "", f'Contract: {doc["termination"]["contract"]}', '"""', _PRELUDE]
    for n in doc["nodes"]:
        abilities = ", ".join(n.get("abilities", []))
        out += [f"def {_fn(n['id'])}(state: dict) -> dict:",
                f'    """speciality: {n["speciality"]} | abilities: {abilities}"""',
                f"    raise NotImplementedError(\"bind speciality '{n['speciality']}'"
                f" (abilities: {abilities})\")", ""]
    out += ["g = StateGraph(dict)"]
    for n in doc["nodes"]:
        out.append(f'g.add_node("{n["id"]}", {_fn(n["id"])})')
    has_in = {e["to"] for e in doc["edges"]}
    has_out: dict[str, list] = {}
    for e in doc["edges"]:
        has_out.setdefault(e["from"], []).append(e)
    for n in doc["nodes"]:
        if n["id"] not in has_in:
            out.append(f'g.add_edge(START, "{n["id"]}")')
    for n in doc["nodes"]:
        edges = has_out.get(n["id"], [])
        if not edges:
            out.append(f'g.add_edge("{n["id"]}", END)')
        elif all(not e.get("when") for e in edges):
            out += [f'g.add_edge("{n["id"]}", "{e["to"]}")' for e in edges]
        else:
            rf = "_route_" + _fn(n["id"])[5:]
            pairs = ", ".join(f'("{e["to"]}", {e.get("when")!r})' for e in edges)
            first_match = n.get("kind") == "router"
            out += [f"def {rf}(state: dict):",
                    f"    hits = [t for t, w in [{pairs}] if w is None or _cond(w, state)]",
                    ("    return hits[0] if hits else END" if first_match
                     else "    return hits or END"),
                    f'g.add_conditional_edges("{n["id"]}", {rf})']
    out += ["", "app = g.compile()", ""]
    return "\n".join(out)
