"""v1.3: compile a graph's declared `triggers` into host-native artifacts.

AGR describes *when a graph wants to run*. It does not become a scheduler — that
would be a product, not a registry. `agr triggers <name> --target <host>` emits
the thing the host already understands: a crontab line, a GitHub Actions
workflow, or a webhook filter.

This module exists because of a rule v1.3 adopted after v1.2's audit: no field
ships without an executing consumer in the same version. `state.schema` was
accepted-and-ignored for two versions, `memory` validated and did nothing, and
`parallel_group` labelled parallelism that did not exist across 17 graphs — each
passed schema, lint and tests. A `triggers` block with no emitter would have been
the fourth.
"""
from __future__ import annotations

import json


class TriggerError(Exception):
    """A trigger cannot be compiled for the requested host."""


def _by(doc: dict, kind: str) -> list[dict]:
    return [t for t in doc.get("triggers") or [] if t["on"] == kind]


def emit_cron(doc: dict) -> str:
    """Crontab lines for every `on: schedule` trigger."""
    rows = _by(doc, "schedule")
    if not rows:
        raise TriggerError(f"'{doc['name']}' declares no schedule trigger")
    out = [f"# {doc['name']} — {doc['description'].splitlines()[0]}"]
    out += [f"{t['cron']} agr eval {doc['name']}" for t in rows]
    return "\n".join(out) + "\n"


def emit_github_actions(doc: dict) -> str:
    """A workflow whose `on:` block mirrors the declared triggers."""
    on: list[str] = []
    for t in _by(doc, "schedule"):
        on += ["  schedule:", f"    - cron: '{t['cron']}'"]
    for t in _by(doc, "webhook"):
        if t.get("source") != "github":
            raise TriggerError(
                f"webhook source '{t.get('source')}' is not github — "
                "use --target webhook for a generic filter"
            )
        on.append(f"  {t['event']}:")
    if not on:
        raise TriggerError(f"'{doc['name']}' declares no schedule or github webhook trigger")
    signals = _by(doc, "signal")
    note = ""
    if signals:
        # Honest about the boundary: a signal is a condition over the blackboard,
        # which no CI `on:` block can evaluate. Saying so beats silently dropping it.
        note = (
            "\n# NOTE: this graph also declares signal trigger(s) that GitHub Actions\n"
            "# cannot express — they are conditions over the graph's own state:\n"
            + "".join(f"#   {t['expr']}\n" for t in signals)
            + "# Evaluate them in the job body, or use --target webhook.\n"
        )
    return (
        f"# Generated by `agr triggers {doc['name']} --target github-actions`\n"
        f"name: {doc['name']}\n"
        "on:\n" + "\n".join(on) + "\n\n"
        "jobs:\n"
        "  run:\n"
        "    runs-on: ubuntu-latest\n"
        "    steps:\n"
        "      - uses: actions/checkout@v4\n"
        "      - uses: astral-sh/setup-uv@v5\n"
        f"      - run: uv run --all-extras agr eval {doc['name']}\n" + note
    )


def emit_webhook(doc: dict) -> str:
    """A generic JSON filter: what an event router would match on."""
    rows = _by(doc, "webhook") + _by(doc, "signal")
    if not rows:
        raise TriggerError(f"'{doc['name']}' declares no webhook or signal trigger")
    return json.dumps({
        "graph": doc["name"],
        "run": f"agr eval {doc['name']}",
        "match": [
            {"source": t["source"], "event": t["event"]} if t["on"] == "webhook"
            else {"condition": t["expr"]}
            for t in rows
        ],
    }, indent=2) + "\n"


EMITTERS = {
    "cron": emit_cron,
    "github-actions": emit_github_actions,
    "webhook": emit_webhook,
}


def emit(doc: dict, target: str) -> str:
    if not doc.get("triggers"):
        raise TriggerError(
            f"'{doc['name']}' declares no triggers — it is a request/response graph"
        )
    return EMITTERS[target](doc)
