"""Report which contracts real models cannot satisfy.

C3 of the v1.3 plan: every graph failing on *every* recorded model is either
fixed or named. The label is derived from the recordings rather than declared in
YAML, so it cannot go stale the way a hand-maintained flag would — and it cannot
be quietly set to make a number look better.
"""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))
from agenticgraphs.evalcmd import eval_graph
from agenticgraphs.registry import ROOT, iter_graphs, load
from agenticgraphs.subgraphs import expand, has_subgraphs
from agenticgraphs.validate import provenance_gaps

OUT = ROOT / "docs" / "contract-findings.md"


def main() -> int:
    rows = []
    for gp in iter_graphs():
        doc = load(gp)
        live = eval_graph(doc["name"], write=False).get("measured_live")
        if not live:
            continue
        rows.append((doc, live))
    if not rows:
        print("no recordings")
        return 0

    unsat = [(d, lv) for d, lv in rows if lv.get("fails_every_model")]
    # Two very different things were sitting in one column. A contract no model
    # satisfies may still be satisfiable — with a binding. One whose evidence has
    # no source in this repo cannot be, and is not a defect: it is a graph waiting
    # for an integration.
    def _gaps(doc):
        return provenance_gaps(expand(doc, ROOT) if has_subgraphs(doc) else doc)

    by_construction = [(d, lv) for d, lv in unsat if _gaps(d)]
    by_model = [(d, lv) for d, lv in unsat if not _gaps(d)]
    split = [(d, lv) for d, lv in rows if lv.get("models_disagree")
             and not lv.get("fails_every_model")]
    clean = [(d, lv) for d, lv in rows if lv["pass_rate"] == 1.0]
    models = sorted({m for _, lv in rows for m in lv.get("models", [])})

    md = [
        "# Contract findings",
        "",
        "Generated by `scripts/gen_contract_findings.py`. Derived from the checked-in",
        "recordings in each graph's `live/`, never hand-maintained — a label that can be set",
        "by hand is a label that can be set to make a number look better.",
        "",
        f"**{len(rows)} graphs recorded across {len(models)} models:** "
        + ", ".join(f"`{m}`" for m in models),
        "",
        f"- ✅ **{len(clean)}** satisfy their contract on every model",
        f"- ⚠️ **{len(split)}** are satisfied by some models and not others",
        f"- 🚫 **{len(by_model)}** are satisfied by no model, but *could* be",
        f"- 🔌 **{len(by_construction)}** are unsatisfiable **by construction** — their "
        "evidence has no source in this repo",
        "",
        "## 🚫 Satisfied by no model",
        "",
        "A contract no model delivers is a bad contract, not a bad model. Each of these",
        "either asks for a key nothing produces, or asserts something the graph never",
        "establishes. They are listed rather than quietly relaxed.",
        "",
        "**Known cause (v1.3 audit F4):** `output` is assembled by the *terminal* node from",
        "facts *upstream* nodes established. Declaring the asserted keys on the terminal —",
        "which was tried, across all three models — asks one node to report facts it never",
        "had. The I/O contract is per-node, the verification contract is graph-level, and",
        "nothing connects them. No lint asks whether the nodes preceding a verifier actually",
        "produce what it asserts on. That is the v1.4 item.",
        "",
    ]
    if unsat:
        md += ["| Graph | Contract | What every model missed |", "|---|---|---|"]
        for d, lv in unsat:
            fails = {f for r in lv["results"] for f in r["assert_failures"]}
            first = sorted(fails)[0] if fails else "—"
            md.append(f"| `{d['name']}` | {d['termination']['contract'][:70]} | `{first[:90]}` |")
    else:
        md.append("*None — every recorded graph is satisfied by at least one model.*")

    md += ["", "## 🔌 Unsatisfiable by construction", "",
           "These assert on a fact no binding here can obtain — a log store, a scanner,",
           "a playbook, an SPDX index. **Not a defect.** A graph waiting for an",
           "integration, listed so it is not mistaken for one pending a fix.", ""]
    if by_construction:
        md += ["| Graph | Evidence it needs |", "|---|---|"]
        for d, _ in by_construction:
            fields = sorted({f for _, fs in _gaps(d) for f in fs})
            md.append(f"| `{d['name']}` | {', '.join(f'`{f}`' for f in fields)} |")
    else:
        md.append("*None.*")

    md += ["", "## ⚠️ Model-dependent", "",
           "Satisfied by some models and not others. This is the column that separates a",
           "weak model from an unsatisfiable contract, and it is why recording more than",
           "one model was the first thing v1.3 did.", ""]
    if split:
        md += ["| Graph | Per-model pass rate |", "|---|---|"]
        for d, lv in split:
            per = ", ".join(f"`{m}` {int(v * 100)}%"
                            for m, v in sorted(lv["per_model_pass_rate"].items()))
            md.append(f"| `{d['name']}` | {per} |")
    else:
        md.append("*None.*")
    md.append("")
    OUT.write_text("\n".join(md))
    print(f"wrote {OUT.relative_to(ROOT)}: {len(clean)} clean, {len(split)} split, {len(unsat)} unsatisfiable")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
