"""Report what the live evidence actually covers, and how load-bearing it is.

Two limits have been stated in the README since v1.3 without ever being measured:
recordings covered 27 of 83 graphs, and each cell was a single sample. This
reports both, so "the registry passes" can never be read off a slice.
"""
from __future__ import annotations

import sys
from collections import Counter
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))
from agenticgraphs.evalcmd import eval_graph  # noqa: E402
from agenticgraphs.registry import ROOT, iter_graphs, load  # noqa: E402
from agenticgraphs.subgraphs import expand, has_subgraphs  # noqa: E402

OUT = ROOT / "docs" / "live-coverage.md"


def main() -> int:
    rows, kinds = [], Counter()
    for gp in iter_graphs():
        doc = load(gp)
        exp = expand(doc, ROOT) if has_subgraphs(doc) else doc
        live = eval_graph(doc["name"]).get("measured_live")
        shape = ("composite" if has_subgraphs(doc)
                 else "human-gated" if any(n.get("kind") == "human" for n in exp["nodes"])
                 else "primitive")
        kinds[(shape, bool(live))] += 1
        rows.append((doc, shape, live))

    lived = [(d, s, lv) for d, s, lv in rows if lv]
    flaky = [(d, lv) for d, _, lv in lived if lv.get("flaky_models")]
    unsat = [(d, lv) for d, _, lv in lived if lv.get("fails_every_model")]
    clean = [(d, lv) for d, _, lv in lived if lv["pass_rate"] == 1.0]
    models = sorted({m for _, _, lv in lived for m in lv.get("models", [])})
    samples = Counter(n for _, _, lv in lived
                      for n in (lv.get("samples_per_model") or {}).values())

    md = [
        "# Live coverage",
        "",
        "Generated by `scripts/gen_breadth_report.py`. What the real-model evidence",
        "actually covers — so a pass rate is never read off a slice and mistaken for",
        "the registry.",
        "",
        f"**{len(lived)} of {len(rows)} graphs recorded**, across "
        + ", ".join(f"`{m}`" for m in models) + ".",
        "",
        "| Graph shape | recorded | not recorded |",
        "|---|---|---|",
    ]
    for shape in ("primitive", "composite", "human-gated"):
        md.append(f"| {shape} | {kinds[(shape, True)]} | {kinds[(shape, False)]} |")
    md += [
        "",
        f"- ✅ **{len(clean)}** satisfied on every model, every sample",
        f"- 🎲 **{len(flaky)}** where one model both passed and failed across samples",
        f"- 🚫 **{len(unsat)}** satisfied by no model",
        "",
        f"Samples per graph+model cell: {dict(sorted(samples.items()))}. A cell with one",
        "sample cannot distinguish a graph that passes from one that passed by luck; 🎲",
        "is what that looks like once there is more than one.",
        "",
    ]
    if flaky:
        md += ["## 🎲 Same model, different answer", "",
               "| Graph | Model | Pass rate across samples |", "|---|---|---|"]
        for d, lv in flaky:
            for m in lv["flaky_models"]:
                n = (lv.get("samples_per_model") or {}).get(m, "?")
                md.append(f"| `{d['name']}` | `{m}` | "
                          f"{int(lv['per_model_pass_rate'][m] * 100)}% of {n} |")
        md.append("")
    if unsat:
        md += ["## 🚫 Satisfied by no model", "", "| Graph | Shape |", "|---|---|"]
        for d, lv in unsat:
            shape = next(s for dd, s, _ in lived if dd["name"] == d["name"])
            md.append(f"| `{d['name']}` | {shape} |")
        md.append("")
    OUT.write_text("\n".join(md))
    print(f"wrote {OUT.relative_to(ROOT)}: {len(lived)}/{len(rows)} recorded, "
          f"{len(clean)} clean, {len(flaky)} flaky, {len(unsat)} unsatisfiable")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
