"""Generate the trace gallery: one docs/traces/<name>.md per graph showing, for
every golden case, the route actually taken, what each node emitted on that
run, and which verification asserts were checked (and whether they passed).

Like gen_scoreboard.py, this re-runs the eval harness itself (via `eval_graph`)
rather than trusting stale profile.json on disk, so the gallery can never drift
from the current graph.yaml / cases.yaml. Also writes docs/traces/README.md as
an index.
"""
from __future__ import annotations

import sys
from pathlib import Path

import yaml

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))
from agenticgraphs.evalcmd import eval_graph
from agenticgraphs.harness import MockRunner
from agenticgraphs.inspect import to_mermaid
from agenticgraphs.registry import ROOT, cases_path, iter_graphs, load

TRACES_DIR = ROOT / "docs" / "traces"


def case_steps(doc: dict, node_outputs: dict, trace: list[str]) -> list[tuple[str, dict]]:
    """Replay a case's fixtures in trace order to show what each visited node emitted."""
    nodes = {n["id"]: n for n in doc["nodes"]}
    runner = MockRunner(node_outputs)
    return [(nid, runner.run(nodes[nid], {})) for nid in trace]


def verification_lines(doc: dict, assert_failures: list[str], skipped_commands: int) -> list[str]:
    lines = []
    failed_prefixes = list(assert_failures)
    for v in doc.get("verification", []):
        if "assert" in v:
            expr = v["assert"]
            hit = next((f for f in failed_prefixes if f == expr or f.startswith(expr + " (")), None)
            lines.append(f"- ❌ `{expr}` — {hit[len(expr):].strip(' ()')}" if hit else f"- ✅ `{expr}`")
        elif "command" in v:
            lines.append(f"- ⏭️ `{v['command']}` — command checks are skipped by the mock runner "
                          "(run with `--live` against a real environment to exercise them)")
    if skipped_commands and not any("⏭️" in l for l in lines):
        lines.append(f"- ⏭️ {skipped_commands} command check(s) skipped by the mock runner")
    return lines


def route_line(trace: list[str]) -> str:
    return " → ".join(f"`{n}`" for n in trace)


def fmt_output(d: dict) -> str:
    if not d:
        return "*(no fixture — empty output)*"
    return "`" + ", ".join(f"{k}={v!r}" for k, v in d.items()) + "`"


def _executable(doc: dict) -> dict:
    """The graph the harness actually runs — subgraph phases inlined.

    A trace of a composite contains the child's prefixed node ids
    (`auto-match.plan`), which do not exist in the authored node list.
    """
    from agenticgraphs.subgraphs import expand, has_subgraphs

    return expand(doc) if has_subgraphs(doc) else doc


def gen_trace_doc(doc: dict, profile: dict, cases: list[dict]) -> str:
    name = doc["name"]
    results = profile["measured"]["results"]
    cases_by_id = {c["id"]: c for c in cases}
    lines = [
        "<!-- generated by scripts/gen_traces.py — edit graph.yaml / cases.yaml, "
        "then `uv run python scripts/gen_traces.py` -->",
        f"# 🔍 Trace gallery · `{name}`",
        "",
        f"> {doc['description']}",
        "",
        f"{len(results)} golden case(s), {sum(r['passed'] for r in results)}/{len(results)} passing "
        f"(`{profile['measured']['runner']}` runner"
        + (", provisional" if profile["measured"]["provisional"] else "") + ").",
        "",
        "## The graph",
        "",
        "```mermaid",
        to_mermaid(doc),
        "```",
        "",
        "## Cases",
        "",
    ]
    for r in results:
        case = cases_by_id[r["id"]]
        steps = case_steps(_executable(doc), case["node_outputs"], r["trace"])
        verdict = "✅ passed" if r["passed"] else "❌ failed"
        lines += [
            f"### `{r['id']}` — {verdict}",
            "",
            f"**Route** ({r['steps']} step(s)): {route_line(r['trace'])}",
            "",
            "| # | Node | Output |",
            "|---|---|---|",
        ]
        for i, (nid, out) in enumerate(steps, start=1):
            lines.append(f"| {i} | `{nid}` | {fmt_output(out)} |")
        lines += ["", "**Verification checked:**", ""]
        lines += verification_lines(doc, r["assert_failures"], r["skipped_command_checks"])
        lines.append("")
    lines += ["---",
              f"*Regenerate: `uv run python scripts/gen_traces.py` · "
              f"[Trace gallery index](README.md) · [Graph card](../../graphs/{doc['category']}/{name}/CARD.md)*",
              ""]
    return "\n".join(lines)


def gen_index(rows: list[dict]) -> str:
    lines = [
        "<!-- generated by scripts/gen_traces.py — do not edit by hand -->",
        "# 🔍 Trace gallery",
        "",
        f"Per-case execution traces for all {len(rows)} graphs: the route taken through the graph, "
        "what each visited node emitted, and which verification asserts were checked. Rendered from "
        "the eval harness's own `RunReport.trace`, so a trace can never claim a route the interpreter "
        "did not actually walk.",
        "",
        "| Graph | Domain | Cases | Pass rate | Trace |",
        "|---|---|---|---|---|",
    ]
    for r in sorted(rows, key=lambda x: (x["category"], x["name"])):
        lines.append(f"| `{r['name']}` | {r['category']} | {r['cases']} | {r['pass_rate'] * 100:.0f}% "
                     f"| [{r['name']}.md]({r['name']}.md) |")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    TRACES_DIR.mkdir(parents=True, exist_ok=True)
    rows = []
    seen = set()
    for gpath in iter_graphs():
        doc = load(gpath)
        name = doc["name"]
        cases_file = cases_path(name)
        if not cases_file.exists():
            continue
        cases = yaml.safe_load(cases_file.read_text())["cases"]
        profile = eval_graph(name)
        (TRACES_DIR / f"{name}.md").write_text(gen_trace_doc(doc, profile, cases))
        seen.add(f"{name}.md")
        rows.append({"name": name, "category": doc["category"],
                     "cases": profile["measured"]["cases"], "pass_rate": profile["measured"]["pass_rate"]})
    (TRACES_DIR / "README.md").write_text(gen_index(rows))
    # remove stale trace files for graphs that no longer have cases (keeps the dir gate-clean)
    for f in TRACES_DIR.glob("*.md"):
        if f.name != "README.md" and f.name not in seen:
            f.unlink()
    print(f"wrote {len(rows)} trace files + docs/traces/README.md")
    return 0


if __name__ == "__main__":
    sys.exit(main())
